name: build

on:
  push:
    branches: [ test ]  
    paths-ignore:
      - README.md

jobs:
  build:
    name: Deploy assets to host
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      
      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Archive assets
        run: dotnet dotnet-combine zip './test-site/' --output './artifacts/release.zip' --extensions  '.*'  --overwrite --verbose

      - name: Deploy archive
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './artifacts/'
          server-dir: 'labs.gowon.ltd/deploy-test/'
          dangerous-clean-slate: true
    
      - name: cPanel extract archive
        shell: pwsh
        run: >-
          Invoke-RestMethod -Uri 'https://${{ secrets.CPANEL_HOST }}/json-api/cpanel?cpanel_jsonapi_apiversion=2&cpanel_jsonapi_module=Fileman&cpanel_jsonapi_func=fileop&op=extract&sourcefiles=/labs.gowon.ltd/deploy-test/release.zip&destfiles=/labs.gowon.ltd/deploy-test&metadata=zip&doubledecode=1' -Method Get -Headers @{'Authorization' = 'cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}'}

      # - name: cPanel delete archive
      #   shell: pwsh
      #   run: >-
      #     Invoke-RestMethod -Uri 'https://${{ secrets.CPANEL_HOST }}/json-api/cpanel?cpanel_jsonapi_apiversion=2&cpanel_jsonapi_module=Fileman&cpanel_jsonapi_func=fileop&op=unlink&sourcefiles=/labs.gowon.ltd/deploy-test/release.zip&doubledecode=1' -Method Get -Headers @{'Authorization' = 'cpanel ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_API_TOKEN }}'}